### ISSUE TITLE
KeyError: 'has_special'

### ISSUE THREAD

**Issue by antonsoroko** [Nemiroff/script.quasar.nova#3]
https://github.com/Nemiroff/script.quasar.nova/blob/686f9c3f46945dd8843d25aeac32d7e099c14233/burst/burst.py#L463
Но ключа has_special нету. 
В елеметовском есть https://github.com/Nemiroff/script.elementum.nova/blob/a1990b966d6a80eb91e3fd5d9e905cd5828946d5/nova/nova.py#L72

Спасибо.

**Comment by Nemiroff** [comment]
В последнем релизе поправил.
